services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  auth:
    image: postgres:16-alpine
    container_name: auth
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'auth'
    volumes:
      - auth-data:/var/lib/postgresql/data

  subscribers:
    container_name: subscribers
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'subscribers'
    volumes:
      - subscribers-data:/var/lib/postgresql/data

volumes:
  auth-data:
  subscribers-data: